//! Phase 9 Task 6: the CI parity leg for the CAUSAL f32 fast twins (spec S4.3) --
//! the exact f64 `BlstmSpectralSegmenter` (`Direction forward` + `Cell_Type
//! slstm|mamba`, driving `nn::cells::{SlstmLayer, MambaLayer}`) vs the f32
//! `FastSpectralSegmenter` (driving `fast::cells::FastCausalNet`), BOTH run through
//! `BagOfProcessors` on the committed phase-9 gate fixtures + the committed synthetic
//! tier-2 corpus audio.
//!
//! The fast path DIVERGES from exact BY DESIGN (f32 + realfft through the feature
//! front-end, f32 through the cell stack and the output MLP -- spec S4). Tolerances
//! are MEASURED first (the `MEASURE` prints, `cargo test -- --nocapture`), then pinned
//! with headroom. Segment COUNT + TYPES identical per channel is the HARD gate: a flip
//! is R1 STOP-and-adjudicate, never a silent widen.
//!
//! WINDOWING. `slstm_forward.config`/`mamba_forward.config` carry `BLSTM_window 0.0`,
//! which resolves to `window_size 0` -- the PLAIN whole-sequence forward on BOTH
//! sides, so no in-test window overlay is needed. That is not a convenience: a causal
//! cell inside a window has its state reset at every window boundary (spec S1.2's
//! "pointless-but-defined"), so window 0 is the only regime the causal fast driver
//! accepts and the only one the Task-7 streaming session can mirror.
//!
//! SUB-SAMPLING AND STACKS ARE LIVE, not bailed: the fixtures run
//! `BLSTM_LSTMSubSampling 4` (a single layer), and `causal_net_supports_stacks_and_
//! sub_sampling` in `fast::cells` covers the multi-layer chain. Both are what the
//! phase's real causal SAD arm needs (`configs/training/lre_sad.toml` is
//! `lstm_neuron_nb = "23,24,24"` / `lstm_sub_sampling = "4,1"`), which is why the fast
//! twins implement `Network::drive`'s chain rather than restricting to ratio 1.
//!
//! THE VACUITY QUESTION (the phase-2b SEG_STRUCT lesson: a decision layer exercised
//! only on non-crossing data proves nothing). MEASURED on the committed fixtures, and
//! it differs per cell:
//!
//! - `mamba_forward` IS already non-vacuous: channel 1 crosses
//!   `BLSTM_decision_thresh_rising 0.6` mid-file and the segmentation carries a real
//!   interior boundary (`Speech@1.1947`).
//! - `slstm_forward` is NOT: its posteriors span `[0.307, 0.870]`, high enough that the
//!   hysteresis latches SPEECH at frame 0 and never falls -- the segmentation reacts
//!   (the head class is Speech, not the seeded Other) but has NO interior boundary, so
//!   a boundary-time comparison on it would compare nothing.
//!
//! PHASE 10 TASK 6 adds the `cfc` rows (`cfc_forward.config` + `cfc_forward_seed.bin`,
//! the committed Task-3 fixture) to every leg below -- the suite is cell-parametric, so
//! this is new ROWS, not new machinery. It is also the INDEPENDENT-IMPLEMENTATION oracle
//! that structurally closes the T3-recorded double-swap residual: the exact
//! `CellLayer::Cfc` arms and the f32 `FastCfc` kernel are two separately-written
//! transcriptions of spec S1.1/S1.2, and a same-direction mistake in the exact tree's
//! enum delegation (a swapped arm, a mis-threaded geometry) no longer cancels out --
//! it would have to be reproduced, identically, in a kernel that shares no code with it.
//!
//! PHASE 10 TASK 8 adds the `lstm` row (`lstm_forward.config` + `lstm_forward_seed.bin`,
//! generated by the same `scripts/extract_phase9_fixtures.py` recipe) -- the FORWARD-ONLY
//! legacy peephole cell, whose f32 twin `fast::cells::FastLstm` completes the causal set.
//! Same parametric legs, one more cell. Note what this row does NOT test: the
//! bidirectional LSTM, whose fast twin is the phase-7 `FastBlstm` and whose parity lives
//! in `phase7_parity_sad.rs`. The two LSTM kernels are separate code (batched faer vs
//! per-step `dot_f32`) and have separate parity legs, deliberately.
//!
//! PHASE 11 TASK 5 adds the `transformer` row (`transformer_forward.config` +
//! `transformer_forward_seed.bin`, the committed Task-4 fixture) whose f32 twin
//! `fast::cells::FastTransformer` is the phase's causal kernel. Same parametric legs, one
//! more cell -- and the same independent-implementation argument the CfC row carries: the
//! exact `CellLayer::Transformer` arms and the f32 kernel are two separately-written
//! transcriptions of the phase-11 spec S1.1/S1.2, so a same-direction mistake cannot
//! cancel out. This row is ALSO the only place the KV RING is exercised against a
//! multi-wrap sequence through the whole driver (50 cell rows at `Transformer_Window 4`,
//! i.e. twelve wraps).
//!
//! [`causal_parity_crossing_is_exercised`] closes the gap uniformly: it sweeps a
//! WEIGHT-SPACE offset on the output layer's single bias -- a pure post-recurrence
//! level shift that leaves every cell weight, and therefore the whole SHAPE of the
//! posterior curve, untouched -- until the segmentation has interior boundaries, then
//! re-asserts exact-vs-fast identity there. It picks `+0.0` for mamba (no edit needed)
//! and `-0.5` for sLSTM (which yields 3 interior boundaries across the two channels,
//! including a full Other -> Speech -> Other on channel 1). The `transformer` row needs a
//! WIDER gain-1 grid, because its seed net saturates and a small level shift moves
//! nothing ([`wide_offsets`]); the `lstm` row needs a SECOND lever -- an output-WEIGHT
//! gain -- because no bias offset whatsoever crosses on that fixture; see [`GAIN_LADDER`]
//! for the measurement and the reason.

use std::path::PathBuf;

use indexmap::IndexMap;
use speech::audio::read_audio;
use speech::cli::{Mode, ModeKind};
use speech::engine::bag_of_processors::{BagOfProcessors, Processor};
use speech::io::binary::{read_weight_vector, write_matrix};
use speech::tasks::segmentation::{SegClass, Segmentation};

fn ref_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/reference_data")
}

fn fixture(rel: &str) -> PathBuf {
    ref_dir().join(rel)
}

fn image_mode() -> Mode {
    Mode {
        kind: ModeKind::Image,
        verbose: false,
    }
}

/// One phase-9 causal fixture config as a map, pointed at the committed seed pack and
/// (optionally) `Inference_Path`. `weights_override` swaps in a locally written pack
/// (the crossing leg).
fn causal_map(
    cell: &str,
    inference: Option<&str>,
    weights_override: Option<&PathBuf>,
) -> IndexMap<String, String> {
    let text = std::fs::read_to_string(fixture(&format!("phase9/{cell}_forward.config"))).unwrap();
    let mut m = speech::legacy_config::parse_legacy_config(&text);
    let pack = match weights_override {
        Some(p) => p.clone(),
        None => fixture(&format!("phase9/{cell}_forward_seed.bin")),
    };
    m.insert(
        "BLSTM_weightsFile".into(),
        pack.to_str().unwrap().to_string(),
    );
    if let Some(p) = inference {
        m.insert("Inference_Path".into(), p.into());
    }
    m
}

/// Run one path (exact when `inference == None`, fast when `Some("fast")`) through the
/// bag on the committed 2 s tier-2 excerpt. Returns the per-channel
/// PRE-`results_to_segmentation` posterior rows + the per-channel segmentations.
fn run_path(
    cell: &str,
    inference: Option<&str>,
    weights_override: Option<&PathBuf>,
) -> (Vec<Vec<f64>>, Vec<Segmentation>) {
    let mut m = causal_map(cell, inference, weights_override);
    let mut bag =
        BagOfProcessors::from_configs(std::slice::from_mut(&mut m), image_mode()).unwrap();

    let mut audio = read_audio(&fixture("phase4a/corpus/f1.wav"), 0.0, 2.0, 0, None).unwrap();
    let dur = (audio.data.ncols() as f64 - 1.0) / audio.sample_rate as f64;
    let n_chan = audio.data.nrows();
    let mut seg: Vec<Segmentation> = (0..n_chan).map(|_| Segmentation::new(dur)).collect();
    bag.run_get_segmentation(0, &mut audio, &mut seg).unwrap();

    let posteriors = match bag.processor(0) {
        Processor::Spectral(s) => s.last_result_rows().to_vec(),
        Processor::FastSpectral(s) => s.last_result_rows().to_vec(),
        _ => panic!("unexpected processor variant for cell={cell} inference={inference:?}"),
    };
    (posteriors, seg)
}

/// Interior boundaries across every channel: segments that are neither the seeded head
/// (`begin == 0`) nor the `End` sentinel -- i.e. genuine mid-file decisions.
fn interior_boundaries(segs: &[Segmentation]) -> usize {
    segs.iter()
        .map(|s| {
            s.segments()
                .iter()
                .filter(|x| x.ty != SegClass::End && x.begin > 0.0)
                .count()
        })
        .sum()
}

/// Compare two runs' posteriors + segmentations. Returns `(max_abs, max_rel, max_dt)`;
/// PANICS on any structural mismatch (count/type/length), which is the R1 hard gate.
fn compare(
    label: &str,
    e: &(Vec<Vec<f64>>, Vec<Segmentation>),
    f: &(Vec<Vec<f64>>, Vec<Segmentation>),
) -> (f64, f64, f64) {
    let (post_e, seg_e) = e;
    let (post_f, seg_f) = f;
    assert_eq!(post_e.len(), post_f.len(), "{label}: channel count");
    assert_eq!(
        seg_e.len(),
        seg_f.len(),
        "{label}: channel count (segments)"
    );

    let mut max_abs = 0.0_f64;
    let mut max_rel = 0.0_f64;
    for chan in 0..post_e.len() {
        assert_eq!(
            post_e[chan].len(),
            post_f[chan].len(),
            "{label}: posterior row length chan {chan}"
        );
        for (&a, &b) in post_e[chan].iter().zip(post_f[chan].iter()) {
            assert!(
                a.is_finite() && b.is_finite(),
                "{label}: non-finite posterior ({a}, {b})"
            );
            let d = (a - b).abs();
            max_abs = max_abs.max(d);
            // Posteriors are logistic outputs in [0,1]; scale by max(|a|, 1e-2) so a
            // tiny posterior does not inflate a tiny absolute delta (the phase-7
            // convention, verbatim).
            max_rel = max_rel.max(d / a.abs().max(1e-2));
        }
    }

    let mut max_dt = 0.0_f64;
    for chan in 0..seg_e.len() {
        let se = seg_e[chan].segments();
        let sf = seg_f[chan].segments();
        assert_eq!(
            se.len(),
            sf.len(),
            "{label}: segment COUNT chan {chan} (R1)"
        );
        for (k, (a, b)) in se.iter().zip(sf.iter()).enumerate() {
            assert_eq!(a.ty, b.ty, "{label}: segment TYPE chan {chan} seg {k} (R1)");
            max_dt = max_dt.max((a.begin - b.begin).abs());
        }
    }
    (max_abs, max_rel, max_dt)
}

// ---------------------------------------------------------------------------
// The CI parity legs.
// ---------------------------------------------------------------------------

/// Every cell the CAUSAL shape now runs. `lstm` joined in phase-10 Task 8
/// ([`speech::fast::cells::FastLstm`]), which completed the phase-9/10 set, and
/// `transformer` in phase-11 Task 5 ([`speech::fast::cells::FastTransformer`]) -- the legs
/// below are parametric, so both rows are new DATA, not new machinery.
const CAUSAL_CELLS: [&str; 5] = ["slstm", "mamba", "cfc", "lstm", "transformer"];

/// The COARSE output-bias offsets [`causal_parity_crossing_is_exercised`] tries first.
/// Phase-9's list verbatim: sLSTM settles at `-0.5` and mamba at `0.0`, so both rows are
/// byte-unchanged by the phase-10 fine-grid extension below.
const COARSE_OFFSETS: [f64; 7] = [0.0, -0.5, -1.0, 0.5, -1.5, 1.0, -2.0];

/// The FINE fallback grid (1/16 steps over `[-1, +1]`), reached only when no coarse
/// offset crosses. THE CfC ROW NEEDS IT, and the reason is a measured property of that
/// fixture worth stating plainly rather than hiding behind a longer list.
///
/// The committed CfC seed net's posterior on the 2 s tier-2 excerpt is FLAT and
/// OSCILLATORY -- it spans `[0.367, 0.705]` at offset 0, with the high region
/// (indices ~5-20) broken by 1-3 frame dips and a uniformly ~0.45 tail. The decision
/// layer's rising/falling pair (0.6 / 0.3) needs a logit swing of ~1.25 to make a round
/// trip, and `min_speech`/`min_silence` 0.2 s (5 rows at this 0.04 s time step) plus
/// 0.1 s padding then erase anything shorter. MEASURED by a 129-point sweep over
/// `[-4, +4]` at 1/16: EXACTLY ONE offset (`-0.0625`) yields an interior boundary, and
/// exactly ONE boundary there.
///
/// So this leg's CfC row is worth precisely what it claims -- ONE real interior
/// boundary, compared bit-for-bit through the shared f64 decision layer (the
/// `MIN_INTERIOR_TYPE1` posture in `phase9_stream_causal.rs`, same shape). It is NOT a
/// rich boundary-set comparison; the sLSTM row (3 boundaries, including a full
/// Other -> Speech -> Other) is. The thinness also means a front-end change that shifts
/// the posterior slightly will make the sweep find NOTHING and PANIC with that exact
/// message -- a loud failure to adjudicate, not a silent weakening.
fn fine_offsets() -> impl Iterator<Item = f64> {
    // The coarse entries are FILTERED OUT: they have already been tried and failed by the
    // time this iterator is reached, so re-running them would be wasted engine
    // invocations.
    (-16i32..=16)
        .map(|k| f64::from(k) * 0.0625)
        .filter(|o| !COARSE_OFFSETS.contains(o))
}

/// MEASURED on this box (M4 Pro / macOS 25.5 / Apple libm) -- see the per-leg prints;
/// the worst across all four (cell x leg) runs is `max_rel 7.74e-6` (mamba), leaving
/// ~13x headroom. Pinned at `measured * 10` rounded up, then widened once for
/// cross-platform realfft/faer SIMD variance (CI is x86, this box is ARM), exactly as the
/// phase-7 SAD leg documents. A FAILURE HERE MEANS RE-MEASURE AND ADJUDICATE, never widen.
///
/// RE-MEASURED by the Phase 10 Task 5 S4 sweep (full-f32 mel at both fast sites): worst
/// `max_rel` 4.13e-6 -> 7.74e-6 (mamba, unchanged leg-for-leg otherwise; slstm 1.40e-6),
/// `max_dt` still EXACTLY 0.0 with boundary count/types identical on every leg, so the
/// PINS ARE UNCHANGED -- the growth is absorbed by the existing headroom.
///
/// PHASE 10 TASK 6 adds the `cfc` rows, MEASURED: plain `max_abs 4.34e-7 / max_rel
/// 6.90e-7`, crossing `max_abs 4.11e-7 / max_rel 6.77e-7`, `max_dt` EXACTLY 0.0 on both
/// with boundary count/types identical. That is the TIGHTEST of the three cells (~145x
/// headroom against these pins, against mamba's ~13x), so the pins stay UNCHANGED here
/// too.
///
/// PHASE 10 TASK 8 adds the `lstm` rows, MEASURED: plain `max_abs 4.40e-7 / max_rel
/// 3.12e-6`, crossing (output gain 3, bias +3) `max_abs 1.30e-6 / max_rel 1.05e-5`,
/// `max_dt` EXACTLY 0.0 on both. That crossing row is now the WORST of the eight
/// (cell x leg) runs -- it displaces mamba's 7.74e-6 -- and it is what these pins are
/// sized for: ~9.5x headroom on the relative pin, ~77x on the absolute. The pins stay
/// UNCHANGED (the growth is absorbed by the existing headroom, the Task-5 precedent), and
/// the reason this row is the worst is structural rather than alarming: the gain lever
/// SHARPENS the logit by 3x, so the same input-side f32 delta lands on a steeper part of
/// the logistic.
///
/// PHASE 11 TASK 5 adds the `transformer` rows, MEASURED: plain `max_abs 5.536e-7 /
/// max_rel 2.351e-6`, crossing (gain 1, bias -5 -- see [`wide_offsets`]) `max_abs
/// 1.602e-6 / max_rel 7.813e-6`, `max_dt` EXACTLY 0.0 on both with boundary count/types
/// identical. Second-worst of the ten (cell x leg) runs behind the LSTM crossing row, and
/// INSIDE the `measured * 10` convention at 12.8x headroom, so the pins stay UNCHANGED
/// here too. Worth recording HOW that headroom was obtained, because it is the general
/// lesson: the row first landed on the gain ladder at `max_rel 1.3120e-5`, whose
/// `measured * 10` would have exceeded this pin -- and the response was to widen the
/// SEARCH (a gain-1 stage that reaches the offsets a saturated fixture needs), never the
/// pin. A row that cannot be brought inside the convention that way is a STOP, not a
/// widening (spec R1).
const POST_REL_PIN: f64 = 1.0e-4;
const POST_ABS_PIN: f64 = 1.0e-4;

#[test]
fn causal_parity_exact_vs_fast() {
    for cell in CAUSAL_CELLS {
        let e = run_path(cell, None, None);
        let f = run_path(cell, Some("fast"), None);
        let (max_abs, max_rel, max_dt) = compare(cell, &e, &f);
        // The posterior SPAN is printed (never asserted) because it is what decides
        // whether the crossing leg below can use a pure level shift or has to reach for
        // the gain ladder: the decision layer's 0.6/0.3 hysteresis needs a ~1.25 LOGIT
        // swing to make a round trip, so a fixture whose span is narrower than that cannot
        // be made to cross by any bias offset whatsoever. See [`GAIN_LADDER`].
        let (lo, hi) = e.0[0]
            .iter()
            .fold((f64::MAX, f64::MIN), |(a, b), &v| (a.min(v), b.max(v)));
        println!(
            "MEASURE {cell} causal exact-vs-fast: max_abs={max_abs:e} max_rel={max_rel:e} \
             max_dt={max_dt} interior={} rows={} span=[{lo:.4}, {hi:.4}] logit_span={:.4}",
            interior_boundaries(&e.1),
            e.0[0].len(),
            (hi / (1.0 - hi)).ln() - (lo / (1.0 - lo)).ln()
        );
        // Non-vacuity of the POSTERIOR comparison: a real sequence, not a constant.
        assert!(e.0[0].len() > 20, "{cell}: too few posterior rows");
        let first = e.0[0][0];
        assert!(
            e.0[0].iter().any(|&v| v != first),
            "{cell}: the exact posterior is constant -- the comparison is vacuous"
        );
        assert!(
            max_abs < POST_ABS_PIN && max_rel < POST_REL_PIN,
            "{cell}: posterior drift max_abs={max_abs:e} max_rel={max_rel:e}"
        );
        // Boundary times come from the SHARED f64 decision layer fed the two posterior
        // vectors; identical crossings give identical times.
        assert_eq!(max_dt, 0.0, "{cell}: boundary max_dt {max_dt} != 0 (R1)");
    }
}

/// THE WIDE gain-1 grid (integer offsets out to `+-16`, SMALLEST MAGNITUDE FIRST), tried
/// after [`fine_offsets`] and before the [`GAIN_LADDER`]. THE TRANSFORMER ROW NEEDS IT
/// (phase-11 Task 5), and the reason is the opposite of the CfC row's:
///
/// The committed transformer seed net SATURATES on the 2 s tier-2 excerpt -- its posterior
/// spans the full `[0.0000, 1.0000]`, a LOGIT span of ~44 (the plain leg prints every
/// cell's, for exactly this diagnosis). A saturated curve is not moved by a small level
/// shift at all: almost every row sits at 0 or 1, so offsets inside `+-2` leave the
/// crossing pattern -- and hence the segmentation -- untouched. What DOES relocate the
/// threshold into the steep region is a LARGE offset, and `-5` is the smallest that does
/// (MEASURED, in this grid's own ascending-magnitude order: `+-2`, `+-3`, `+-4` and `+5`
/// all yield zero interior boundaries; `-5` yields TWO).
///
/// Without this stage the row escalated to the gain ladder (`gain 2, bias -8`) and paid
/// for it twice over: the gain SHARPENS the logit, landing the same input-side f32 delta
/// on a steeper part of the logistic, so the crossing row measured `max_rel 1.3120e-5`
/// against the `1.0e-4` pin -- passing, but with the least headroom of any row -- while
/// finding only ONE interior boundary. At gain 1 the same row measures `max_rel 7.813e-6`
/// (1.68x tighter, back inside the house `measured * 10` convention) with TWO boundaries,
/// AND it keeps phase-9's pure level-shift property: every cell weight untouched, the
/// whole SHAPE of the posterior still produced by the causal stack. Better on all three
/// counts, which is why the fix was to widen the SEARCH rather than the PIN.
///
/// SIBLING ROWS ARE BYTE-UNCHANGED, by construction and verified by their printed rungs:
/// slstm (`-0.5`), mamba (`0.0`) and cfc (`-0.0625`) all break out in an EARLIER stage, and
/// the LSTM row finds nothing here for the reason [`GAIN_LADDER`] documents and measures
/// (a 129-point sweep over `[-16, +16]` at 0.25 -- which strictly contains this grid --
/// yields ZERO interior boundaries at gain 1), so it still escalates to `gain 3, bias +3`.
fn wide_offsets() -> impl Iterator<Item = f64> {
    // Smallest magnitude first, alternating sign: the ladder's philosophy is "use the
    // fixture as committed, every step is a fallback", so the least perturbation that
    // works is the one to take. `-2.0` is already in [`COARSE_OFFSETS`] and is filtered.
    (2i32..=16)
        .flat_map(|m| [-f64::from(m), f64::from(m)])
        .filter(|o| !COARSE_OFFSETS.contains(o))
}

/// THE OUTPUT-GAIN LADDER, reached only when NO bias offset crosses at gain 1 -- which
/// on the committed fixtures means the LSTM row and nothing else (phase-10 Task 8;
/// phase-11's transformer row was ALSO here until [`wide_offsets`] pulled it back to
/// gain 1).
///
/// WHY THE BIAS ALONE CANNOT DO IT THERE, measured rather than assumed: a 129-point bias
/// sweep over `[-16, +16]` at 0.25 yields ZERO interior boundaries at EVERY offset, even
/// though the posterior traverses the full `[0, 1]` range across that sweep. The reason is
/// the SHAPE of this net's posterior on the 2 s excerpt -- its highest rows are its
/// EARLIEST, so as the level rises the hysteresis latches SPEECH at frame 0 and the whole
/// file becomes one segment; as it falls, nothing ever crosses. A pure level shift cannot
/// manufacture an interior edge out of a monotone-onset curve.
///
/// What CAN: scaling the output layer's four weights, which multiplies the logit's
/// VARIABLE part while leaving the bias to re-centre it. That is the same class of
/// intervention as the bias sweep -- OUTPUT-LAYER ONLY, post-recurrence, every cell weight
/// untouched, so the causal stack still produces the entire shape of the curve -- it
/// sharpens the contrast rather than moving the level.
///
/// Ordered `3` first because a 2-D (gain x offset) probe measured it as the rung with the
/// RICHEST boundary set (gain 3 / offset +3.0 -> 3 interior boundaries, posterior span
/// `[0.014, 0.842]`, i.e. sharpened but not saturated), against gain 2's single boundary.
/// That ordering is a test-QUALITY choice, not a correctness one.
const GAIN_LADDER: [f64; 4] = [3.0, 2.0, 4.0, 6.0];

/// The offset grid the gain ladder sweeps (`[-8, +8]` at 0.5). Wider and coarser than the
/// gain-1 lists, because a scaled logit needs a proportionally larger re-centring.
fn ladder_offsets() -> impl Iterator<Item = f64> {
    (-16i32..=16).map(|k| f64::from(k) * 0.5)
}

/// THE DECISION-LAYER leg (see the module doc's vacuity note). Sweeps the output MLP's
/// single bias -- a post-recurrence level shift, so the causal stack still produces the
/// whole SHAPE of the posterior curve -- and, if no offset crosses, escalates to the
/// [`GAIN_LADDER`]; then asserts that exact and fast agree on segment count, types and
/// times EXACTLY on the run that crosses.
#[test]
fn causal_parity_crossing_is_exercised() {
    let tmp = tempfile::tempdir().unwrap();
    for cell in CAUSAL_CELLS {
        // The output layer's bias is the LAST weight before the `2*input_size`
        // normalize tail (pack layout `[stack | output MLP | mean | std]`, and the
        // fixture's output MLP is a single `4 -> 1` layer: 4 weights then 1 bias). The
        // tail length is DERIVED from the config's own `BLSTM_LSTMNeuronNb[0]`, not
        // hardcoded, so a fixture regeneration at a different input width relocates the
        // index instead of silently perturbing some interior weight.
        let input_size: usize = causal_map(cell, None, None)["BLSTM_LSTMNeuronNb"]
            .split(',')
            .next()
            .unwrap()
            .trim()
            .parse()
            .unwrap();
        let seed = fixture(&format!("phase9/{cell}_forward_seed.bin"));
        let base = read_weight_vector(&seed).unwrap();
        let bias_idx = base.len() - 2 * input_size - 1;
        let path = tmp.path().join(format!("{cell}_crossing.bin"));
        // The four output weights sit immediately before that bias.
        let lever = |gain: f64, offset: f64| -> Vec<f64> {
            let mut probe = base.clone();
            for w in probe.iter_mut().take(bias_idx).skip(bias_idx - 4) {
                *w *= gain;
            }
            probe[bias_idx] += offset;
            probe
        };

        // GAIN 1 FIRST with `0.0` first within it, so a fixture that already crosses is
        // used AS COMMITTED and every sweep step is a fallback rather than a default
        // detour. COARSE steps first (slstm settles at -0.5 and mamba at 0.0, both inside
        // the original list, so those rows are byte-unchanged by the phase-10/11
        // extensions), then a FINE 1/16 grid over `[-1, +1]` (the CfC row's, see
        // [`fine_offsets`]), then the WIDE integer grid out to `+-16` (the transformer
        // row's, see [`wide_offsets`]), and only then the [`GAIN_LADDER`] (the LSTM row's,
        // the one fixture no level shift can crack).
        let gain1 = COARSE_OFFSETS
            .iter()
            .copied()
            .chain(fine_offsets())
            .chain(wide_offsets())
            .map(|o| (1.0_f64, o));
        let escalation = GAIN_LADDER
            .iter()
            .copied()
            .flat_map(|g| ladder_offsets().map(move |o| (g, o)));

        let mut chosen: Option<(f64, f64, usize)> = None;
        for (gain, offset) in gain1.chain(escalation) {
            let probe = lever(gain, offset);
            write_matrix(&path, probe.len(), 1, &probe).unwrap();
            let interior = interior_boundaries(&run_path(cell, None, Some(&path)).1);
            if interior > 0 {
                println!(
                    "MEASURE crossing[{cell}]: output gain {gain} bias offset {offset:+} -> \
                     {interior} interior boundaries"
                );
                chosen = Some((gain, offset, interior));
                break;
            }
        }
        let (gain, offset, want_interior) = chosen.unwrap_or_else(|| {
            panic!("{cell}: no (output gain, bias offset) pair produced an interior boundary")
        });

        let flat = lever(gain, offset);
        write_matrix(&path, flat.len(), 1, &flat).unwrap();

        let e = run_path(cell, None, Some(&path));
        let f = run_path(cell, Some("fast"), Some(&path));
        let (max_abs, max_rel, max_dt) = compare(&format!("{cell}/crossing"), &e, &f);
        let interior = interior_boundaries(&e.1);
        println!(
            "MEASURE {cell} causal CROSSING (output gain {gain}, bias {offset:+}): \
             max_abs={max_abs:e} max_rel={max_rel:e} max_dt={max_dt} interior={interior}"
        );
        assert_eq!(
            interior, want_interior,
            "{cell}: the sweep is not reproducible"
        );
        assert!(
            interior > 0,
            "{cell}: the decision-layer comparison is vacuous"
        );
        assert!(
            max_abs < POST_ABS_PIN && max_rel < POST_REL_PIN,
            "{cell}: crossing posterior drift max_abs={max_abs:e} max_rel={max_rel:e}"
        );
        assert_eq!(
            max_dt, 0.0,
            "{cell}: crossing boundary max_dt {max_dt} != 0 (R1)"
        );
    }
}

/// The dispatch table: what the fast tree now BUILDS, and the two combinations it still
/// refuses (spec S4.2). The bail legs point `BLSTM_weightsFile` at nothing, so the
/// SHAPE check is what fires -- not a pack-length mismatch downstream of it.
#[test]
fn fast_dispatch_bails_and_builds_per_cell_and_direction() {
    let build = |m: &mut IndexMap<String, String>| -> anyhow::Result<BagOfProcessors> {
        BagOfProcessors::from_configs(std::slice::from_mut(m), image_mode())
    };

    // ACCEPTED: all FOUR causal cells build a fast net, from their committed packs
    // (`cfc` joined in phase-10 Task 6, which replaced its interim `element_count` bail
    // with a real `FastCfc`; `lstm` in Task 8, which replaced the LAST shape bail with a
    // real `FastLstm` -- see the flipped block below).
    for cell in CAUSAL_CELLS {
        let mut m = causal_map(cell, Some("fast"), None);
        let bag = build(&mut m).unwrap_or_else(|e| panic!("fast + causal {cell} must build: {e}"));
        assert!(
            matches!(bag.processor(0), Processor::FastSpectral(_)),
            "{cell}: expected the fast SAD driver"
        );
    }

    // WAS BAILED (1), NOW BUILDS: a new cell in the BIDIRECTIONAL direction. Phase-10
    // Task 7 landed `fast::bicell::FastBiCell`, so this combination is a supported shape
    // rather than a named follow-on; its parity legs live in
    // `tests/phase10_bicell_parity.rs` (which drives the committed BIDIRECTIONAL
    // fixtures, not these forward ones). Kept here as the DISPATCH statement: the
    // forward-fixture config, re-declared bidirectional, must now classify and build.
    for cell in ["slstm", "mamba", "cfc"] {
        let mut m = causal_map(cell, Some("fast"), None);
        m.insert("BLSTM_Direction".into(), "bidirectional".into());
        // A bidirectional net's output MLP consumes 2*hidden, so widen it or
        // `BlstmConfig::from_legacy` rejects the config before the fast dispatch runs.
        m.insert("BLSTM_OutputNeuronNb".into(), "8,1".into());
        // Point at the matching BIDIRECTIONAL pack: this shape carries TWO recurrent
        // stacks, and the forward-sized seed is short by exactly one of them (the
        // length check that leg is pinned by, in the phase-10 suite).
        m.insert(
            "BLSTM_weightsFile".into(),
            fixture(&format!("phase9/{cell}_bidirectional_seed.bin"))
                .to_str()
                .unwrap()
                .to_string(),
        );
        let bag =
            build(&mut m).unwrap_or_else(|e| panic!("fast + bidirectional {cell} must build: {e}"));
        assert!(
            matches!(bag.processor(0), Processor::FastSpectral(_)),
            "{cell}: expected the fast SAD driver"
        );
    }

    // STILL BAILED, and where it matters most: STREAMING. A bidirectional net is
    // unstreamable by construction (the reverse pass reads the whole sequence), so the
    // shape the offline tree now builds must still be refused there -- the phase-8 /
    // phase-9 streaming legs pin the message body UNMODIFIED, and this asserts the same
    // contract from the cell-parametric side.
    for cell in ["slstm", "mamba", "cfc"] {
        let mut m = causal_map(cell, Some("fast"), None);
        m.insert("BLSTM_Direction".into(), "bidirectional".into());
        m.insert("BLSTM_OutputNeuronNb".into(), "8,1".into());
        // The streaming session's own earlier bails (algo 3, mono, frozen gain) come
        // BEFORE the shape dispatch, so the config has to clear them or this leg would
        // pass on the wrong bail.
        m.insert("Audio_fixed_gain".into(), "0.5".into());
        let err = speech::fast::stream::StreamingSession::new(&m, 8000.0, 1)
            .err()
            .unwrap_or_else(|| panic!("streaming + bidirectional {cell} must bail"));
        let msg = err.to_string();
        assert!(
            msg.contains(&format!(
                "cell type '{cell}' is not supported on the fast inference path"
            )) && msg.contains("BIDIRECTIONAL"),
            "expected a bidirectional-streaming bail for {cell}, got: {err}"
        );
    }

    // WAS BAILED (2), NOW BUILDS: the causal direction with the LEGACY LSTM cell. This
    // was the LAST shape refusal in `classify_fast_shape` -- phase-10 Task 8 landed
    // `fast::cells::FastLstm`, so the classifier is TOTAL and there is no shape bail left
    // to assert. The accepted loop above already covers the happy path from the committed
    // `lstm_forward` fixture; what this pins is the two things that flip would break if it
    // were done carelessly.
    //
    // (a) The pack must be read as an LSTM pack, not head-first as some other cell's. A
    //     causal net built from the SLSTM fixture's pack under `Cell_Type lstm` has a
    //     different `element_count` (1651 vs 1603), so it must fail on LENGTH rather than
    //     quietly running an sLSTM's weights through a peephole-LSTM kernel.
    let mut m = causal_map("slstm", Some("fast"), None);
    m.insert("BLSTM_Cell_Type".into(), "lstm".into());
    let err = build(&mut m)
        .err()
        .unwrap_or_else(|| panic!("an sLSTM-sized pack must not decode as an LSTM"));
    assert!(
        err.to_string().contains("too short"),
        "expected a pack-length bail, got: {err}"
    );

    // (b) ...and the EXACT path still builds the same shape, as it always did (the fast
    //     side is now its equal rather than a documented gap).
    let mut exact = causal_map("lstm", Some("exact"), None);
    build(&mut exact).expect("Inference_Path exact + causal LSTM must build");
}

/// A causal fast net runs WINDOW 0 and nothing else: windowing resets a causal cell's
/// state at every boundary (spec S1.2), and the streaming session forbids it outright
/// (S5.3). Pinned at `get_segmentation`, where the window is resolved.
///
/// NOTE (Task 6 finding, reported not fixed -- it is exact-tree code and out of this
/// task's scope): the EXACT tree does not merely find this regime pointless, it PANICS
/// on it. `feed_forward_backward_overlap`'s final quotient loop (`nn/blstm.rs:1974`)
/// reproduces the legacy quirk of bounding BOTH the forward and backward accumulators
/// by `_OutputForward.cols()`, and a `Direction::Forward` net's backward accumulator is
/// ZERO-width -> `ndarray: index out of bounds`. Measured: `slstm_forward.config` with
/// `BLSTM_window 0.5` panics on the exact path, while the same edit on
/// `slstm_bidirectional.config` runs clean, so it is causal-specific. The fast bail
/// below is therefore strictly the better behaviour of the two, and this test asserts
/// only the fast side.
#[test]
fn fast_causal_bails_on_windowed_inference() {
    let mut m = causal_map("slstm", Some("fast"), None);
    // 0.5 s window at 8 kHz with spectrum_shift 0.01 -> window_size 25: a genuinely
    // windowed dispatch, not a degenerate one.
    m.insert("BLSTM_window".into(), "0.5".into());
    let mut bag =
        BagOfProcessors::from_configs(std::slice::from_mut(&mut m), image_mode()).unwrap();
    let mut audio = read_audio(&fixture("phase4a/corpus/f1.wav"), 0.0, 2.0, 0, None).unwrap();
    let dur = (audio.data.ncols() as f64 - 1.0) / audio.sample_rate as f64;
    let n_chan = audio.data.nrows();
    let mut seg: Vec<Segmentation> = (0..n_chan).map(|_| Segmentation::new(dur)).collect();
    let err = bag
        .run_get_segmentation(0, &mut audio, &mut seg)
        .err()
        .unwrap_or_else(|| panic!("fast causal + windowed inference must bail"));
    assert!(
        err.to_string()
            .contains("windowed inference is unsupported"),
        "expected a causal-window bail, got: {err}"
    );
}
